### ISSUE TITLE
Using Asset's data to create visualization

### ISSUE THREAD

**Issue by Extarys** [audiocogs/aurora.js#120]
Hi!

First of all, I'm a total noob to aurora.js, I discovered it yesterday and I'm still trying to figure everything out...

I tried to create a very basic music visualization with bars... Using the `data` event from the `asset` object, I'm able to draw the visialization, but it doesn't feel right. What I mean is, the bars do not represent the music, a strong bass song with no lyrics or an opera show very similar effect.

For exemple, one bar out of two is two times higher than all others.
I tried to get my samples from the whole array, I tried splitting it in half, etc but I don'T really know what I'm doing.

Here's a sample code:

	var barsArr = []; //Hold allt he bars
	var samples = 50; //Number of bars to show
	height = 100;
				
	//Visual
	barsEl = document.getElementById('playerVisualizer');
	for(var i = 0; i < samples; i++ ){
		var nunode = document.createElement('div');
		nunode.classList.add('bar');
		nunode.style.left = (5 * i + (1.01*i)) + 'px';
		barsArr.push(nunode);
		barsEl.appendChild(nunode);
	}
				
	var max = 100;
	var canCall = false;
	var timer = setInterval(function(){
		canCall = true;
	}, 250);
	var renderFrame = function(frequencyData) {
		
		if(canCall) { //Throttle refresh
			canCall = false;
			
			//console.log("frequencyData length: "+frequencyData.length);
			for(var i = 0; i < barsArr.length; i++) {
				// frequencyData.length is 8192
				//Divide by 32
				samplingBase = Math.floor(frequencyData.length / 32 / barsArr.length);
				
				s = samplingBase*i; //Get sampling
				var bar = barsArr[i];
				bar.style.height = (((frequencyData[s]*100)/max)*height + 'px');
			}
		}
	};
				
	player.asset.on('data', function(data) {
		//console.log(data);
		renderFrame(data);
	});

If there's someone who can help me, it would be fantastic.
By the way, aurora.js is an amazing work. Good job!

**Comment by crackofdusk** [comment]
Hi @Extarys!

It feels wrong because you are not reading frequency data. The aurora.js callback you're using returns PCM (see: https://github.com/audiocogs/aurora.js/wiki/Asset-Class-Reference#-data-buffer)

What you are visualizing in your example is time domain data. What you need is frequency domain data. You can convert between the two using Fourier transforms. Check Wikipedia or other sources for more information on the Fourier Transform. The good news is that you don't have to program the Fourier transform yourself, you can use [fft.js](https://github.com/JensNockert/fft.js).

Because not all frequencies are equally "important" (it is harder for the human ear to distinguish higher frequencies) you need to do frequency spectrum compression. Put ranges of frequencies into bins. Lower frequency bins should be smaller than higher frequency bins, because you want to compress higher frequencies more. I don't know/remember what separation is best, but try modeling the number of frequencies per bin as a logarithm.

Take a look at what I did here: https://github.com/crackofdusk/glitchy-space/blob/a3d8cbb8df541bc7bc21d4a8216e9d70cf6efd33/js/player.js#L90-L134

I'm doing a different kind of visualization but I'm still using the frequency domain representation. I have to admin I don't remember what the code in `process` does exactly, but it's some trick @jussi-kalliokoski taught me.

Also note my code uses [filters](https://github.com/audiocogs/aurora.js/wiki/Player-Class-Reference#-avplayerfilters) to do the processing.I think @devongovett said it would give better performance.

Hope that helps!

**Comment by Extarys** [comment]
Hehe I knew it was PCM data, but I was probably too tired to even think about it :)

Thank you @crackofdusk, I'll have some fun today! :+1:
