### ISSUE TITLE
Using aurora with HTML5 Audio tag?

### ISSUE THREAD

**Issue by nickcartery** [audiocogs/aurora.js#139]
Hi,

I'm getting a trouble with my music app when mobile screen turns off. CPU goes down (sleep)... I get a new idea to solve it: decode and push it into HTML5 Audio tags.

<audio src="push_data_decoded_and_play_it_via_this_tag"></audio>

Is possible?

Many thanks,

**Comment by dest4131** [comment]
Why do you use Aurora if you can fetch audio directly with an HTML5 audio tag, which accurately handles the decoding?

From what I believe to understand, using both of them simultaneously is not possible, by design. HTML5 audio tags and JS live in different worlds.
JS is limited by CORS (cross origin) policy for security reasons, while HTML5 audio is not. The application of CORS policy leads to block communication between JS and HTML5 audio.

**Comment by tchakabam** [comment]
that's not entirely true, you can use `MediaSourceExtension`. it is an interface to the decoder which will allow you to pass in media data to decode and play it via an audio/video media element i.e tag. that's probably what @nickcartery wants? But that is using exactly the same path that the browser uses otherwise to decoder? What format/codec are you talking off=

also this stuff here (Aurora) is not even using MediaSource, its using WebAudio, it decodes stuff in JS into raw frames.

but i don't think that will solve your CPU issues :D actually decoding stuff in JS is much more expensive that doing it via any browser API i.e MediaSource or directly setting a src to the audio tag.

**Comment by tchakabam** [comment]
@dest4131 CORS has nothing to do with that.

**Comment by dest4131** [comment]
I stand corrected!

**Comment by daslicht** [comment]
How about playing an ogg stream in safari on osx ? Ogg is not supported by safari. Feasible ?
Where we are at it , is it possible to get embedded vorbis comments ?
