### ISSUE TITLE
Extracting Stereo channel data

### ISSUE THREAD

**Issue by Kage1989** [audiocogs/aurora.js#144]
I would like to extract out the stereo channel data, similar to `AudioBuffer.getChannelData()`. But I don't see any reference to where I could get the data for each individual channel. Much appreciated if anyone could point me in the right direction to do so.

Also, I've noticed that the BufferList.availableBytes does not correspond to the file size of the audio file. I'm curious why this is so. May I ask if this is a bug?

**Comment by devongovett** [comment]
The data emitted by AV.Asset is interleaved, meaning that it is a single buffer containing both channels in a L R L R L... pattern. You can separate those into two buffers pretty easily yourself.

BufferList#availableBytes it is the number of bytes currently available for reading. This would change as the file is streamed in, and as you read the file since those bytes have been consumed. The total file size is not currently accessible anywhere because some sources are continuous.
