### ISSUE TITLE
Http stream mode play instance

### ISSUE THREAD

**Issue by nampdn** [audiocogs/aurora.js#147]
Could we play instance a big file (~50mb) through http stream by using `fromURL` constructor without waiting for downloading the first chunk (~1mb) ?

**Comment by devongovett** [comment]
You could subclass and change the chunk size here https://github.com/audiocogs/aurora.js/blob/master/src/sources/browser/http.coffee#L6.

However, we do need a large enough chunk size in order to probe correctly in a single chunk, and mp3s especially need a large size since ID3 data is often at the start of the file that we need to skip.
