### ISSUE TITLE
Set the chunk while downloading file

### ISSUE THREAD

**Issue by fatshotty** [audiocogs/aurora.js#17]
Hello,

I noticed that aurora.js will try to download entire file by making several requests using 1Mb of bytes array chunk.
In my cases I have large m4a files (around 40/50Mb), so this results on aurora.js making 40~50 requests to obtain whole file. This stresses too much the server.
I wonder if there is a way to set the size of the file chunk while downloading?

I think chunks of 1Mb is good for first few requests (just to obtain needed bytes to start streaming), but subsequents chunks can be larger, maybe progressively increased (?).

IE:

```
first request chunk of 1Mb
second request chunk of 3Mb
third request chunk of 5Mb
fourth request chunk of 8Mb .....
// and so on ....
```

It should be nice to implement this alongside with #4

Thanks in advance

**Comment by filerun** [comment]
Years later I am having the same problem. The average file size of a FLAC track is 30 MB. That means 30 requests from a single user. Not only that, but because Internet speeds nowdays are quite high, some network filters my block the user thinking its a denial-of-service attack. Apparently the only chunk needed for starting the playback is the first one. It would be great to just download 1MB and the rest of the file entirely.

**Comment by fatshotty** [comment]
hi @filerun 
I added this lines of code in my project and it works fine.


```
AV.HTTPSource.DEFAULT_CHUNK_SIZE = 1 << 20;

var old_loop = AV.HTTPSource.prototype.loop;
AV.HTTPSource.prototype.loop = function(){
  this.chunkSize += this.chunkSize / 2;
  old_loop.apply(this, arguments);
};
```
In this way `chunkSize` is progressively incremented

Hope this helps

Fabio
